[project]
name = "audio-jepa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hydra-core>=1.3.2",
    "numpy>=2.2.6",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
    "wandb>=0.25.0",
]
